development:
  adapter: postgresql
  database: tic_tac_with_friends_development

test:
  adapter: postgresql
  database: tic_tac_with_friends_test

production:
  adapter: postgresql
  database: tic_tac_with_friends_production
